- docs/index.asciidoc
- docs/troubleshooting.asciidoc
Adds a boilerplate troubleshooting page
> docs: add troubleshooting page

- docs/setup.asciidoc
corrected package example
corrected AgentConfiguration example with proper attribute names
corrected URL vs Host terms
enumerated platform requirements
> Updated setup.asciidoc

- docs/intro.asciidoc
Backports https://github.com/elastic/apm-agent-ios/pull/63 to 0.x
> [0.x] Doc link fixes

- NOTICE.txt
> added NOTICE.txt

- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/AgentConfiguration.swift
- docs/configuration.asciidoc
- docs/setup.asciidoc
- docs/supported-tech.asciidoc
> improved agent start to use url rather than host

- docs/configuration.asciidoc
- docs/intro.asciidoc
- docs/setup.asciidoc
Added additional docs covering new view instrumentation and linked to new open telemetry docs
> Doc and config

- CHANGELOG.asciidoc
- RELEASE.md
- Sources/apm-agent-ios/Version.swift
- docs/setup.asciidoc
updated version file
added RELEASE.md
> updated release notes

- Sources/Tests/apm-agent-iosTests/AgentEnvResourceTests.swift
- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/AgentEnvResource.swift
- Sources/apm-agent-ios/AgentResource.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
This provides support for #149
> fixed interface with Otel Envar setters

- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/Instrumentation/Lifecycle/ApplicationLifecycleInstrumentation.swift
- Sources/apm-agent-ios/InstrumentationConfigBuilder.swift
- Sources/apm-agent-ios/InstrumentationConfiguration.swift
- Sources/apm-agent-ios/InstrumentationWrapper.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticSpanProcessor.swift
> Applicaiton lifecycle

- Package.swift
- Sources/Tests/apm-agent-iosTests/CentralConfigTests.swift
- Sources/Tests/apm-agent-iosTests/SessionSamplerTest.swift
- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/AgentConfiguration.swift
- Sources/apm-agent-ios/Configuration/CentralConfigData.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
- Sources/apm-agent-ios/Session/SessionSampler.swift
- docs/configuration.asciidoc
- docs/images/dynamic-config.svg
This PR adds sample rate to the agent configuration, allowing sample rate to be set without central config.
> added local config for sample rate

- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/AgentConfiguration.swift
- Sources/apm-agent-ios/InstrumentationConfigBuilder.swift
- Sources/apm-agent-ios/InstrumentationConfiguration.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
- docs/configuration.asciidoc
This PR exposes configuration for the persistent store through the instrumentation configuration object.
> added config option for storage parameters

- docs/index.asciidoc
- docs/instrumentation.asciidoc
> added instrumentation doc to doc index

- Package.swift
- Sources/apm-agent-ios/InstrumentationWrapper.swift
This PR creates an "error" for http errors, which will then show up in the errors tab of the UI.
> Http errors

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
- .github/workflows/opentelemetry.yml
- CHANGELOG.asciidoc
- Package.swift
- README.md
- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/Utils/NTPClock.swift
- docs/release-notes.asciidoc
**Release of v1.0.1**
- fixed memory leaks related to NTP usage
> Main -> 1.x

- Sources/apm-agent-ios/Resources/PrivacyInfo.xcprivacy
- purpose of data collected updated from "Analytics" to "AppFunctionality"
> PrivacyManifest file updates

- Sources/apm-agent-ios/Utils/NTPClock.swift
This fixes logs occurring every time the ntp clock is called, and improves log categorization.
> fixed ntp clock logging to only occur once

- .github/workflows/macos.yml
- CHANGELOG.asciidoc
- Package.swift
- Sources/apm-agent-ios/Version.swift
- docs/setup.asciidoc
- docs/supported-tech.asciidoc
This ought to fix #245 #242 #243
> v1.2.0 Release

- CHANGELOG.asciidoc
- Sources/apm-agent-ios/Version.swift
- docs/setup.asciidoc
- docs/supported-tech.asciidoc
> release v1.2.1

- docs/release-notes/known-issues.md
- Specifies no known issues
- Adds short description to known issues page
> [DOCS] Updates blank known issues page

- .github/CODEOWNERS
- docs/docset.yml
- docs/release-notes/index.md
- docs/release-notes/known-issues.md
This prepares the iOS release notes for https://github.com/elastic/opentelemetry-dev/issues/923
> Prepare release notes for migration

- Package.swift
- Sources/Tests/apm-agent-iosTests/ApplicationLifecycleInstrumentationTest.swift
- Sources/Tests/apm-agent-iosTests/ElasticLogRecordProcessorTest.swift
- Sources/Tests/apm-agent-iosTests/ElasticSpanProcessorTest.swift
- Sources/Tests/apm-agent-iosTests/Interceptor/InterceptorTests.swift
- Sources/Tests/apm-agent-iosTests/SessionSpanProcessorTest.swift
- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/AgentConfiguration.swift
- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticLogRecordProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticMetricProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticSpanProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/Interceptor/ClosureInterceptor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/Interceptor/Interceptor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/Interceptor/MultiInterceptor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/Interceptor/NoopInterceptor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/SignalFilter.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
- docs/reference/configuration.md
- docs/reference/set-up-apm-ios-agent.md
This PR implements a signal-interceptor interface for adding or modifying attributes on Spans and LogRecords during the Processor stage. 
Additionally, this PR undoes some attempts at providing this functionality in the signal filters.
> Signal interceptors

- docs/docset.yml
- docs/redirects.yml
Required before #272 is merged.
> Add redirects
