elastic/apm-agent-ios

- .ci/jobs/apm-agent-ios-mbp.yml
- README.md
JJBB syntax was incorrect, I used the wrong template :/
I also found the name of the default branch is `main`, so I changed the badge reference too.
> JJBB: fix missing project type and main

- .ci/Jenkinsfile
Use the [macosx-10.15](https://apm-ci.elastic.co/label/macosx-10.15/) label that got installed the xcode tooling
> [CI] use the macos with xcode

- README.md
- docs/page_header.html
* Links from the project repo to the public documentation
* Adds a banner to the top of the public documentation:
For https://github.com/elastic/apm-agent-ios/issues/13
> docs: Add disclaimer and link

- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/AgentResource.swift
host.id is being mapped to a System.ID https://github.com/elastic/apm-server/blob/01a12f2b3ebfa78c2186270eb4771c6ff1d7a27b/model/system.go
which doesn't get mapped to any fields in ES. This PR adds device.id as a temporary fix.
> added device.id to AgentResource

- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/AgentEnvResource.swift
This pr ensures that resource env-vars are properly passed to the agent, and not allowing otel defaults to override the agent resource.
> added agent envar

- Package.resolved
- Package.swift
- Sources/apm-agent-ios/Agent.swift
updated deprecated GRPC library `secure` api -> `usingPlatformAppropriateTLS`
> OpenTelemetry-Swift -> v1.1.0

- docs/intro.asciidoc
Links updated as per elastic/observability-docs#1385. The old links will break when 7.17 releases. This PR and all backports must be merged before the 7.17 release. Thanks!
> docs: update broken links for apm-guide-ref

- .github/workflows/macos.yml
We are in the transition to use ephemeral workers, but until then there is a requirement to decommission the existing MacOS workers. For such this proposal uses GitHub actions for MacOS until we can use the ephemeral workers.
> ci: use github actions macos

- Package.resolved
- README.md
- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/Instrumentation/ActivityStack.swift
- Sources/apm-agent-ios/Instrumentation/SimpleActivityContextManager.swift
- Sources/apm-agent-ios/Instrumentation/TraceLogger.swift
- Sources/apm-agent-ios/Instrumentation/UIApplicationInstrumentation.swift
- Sources/apm-agent-ios/Instrumentation/ViewControllerInstrumentation.swift
current view controller span is internally managed in instrumentation.
Context propagation is still not working quite right, which results in missing sub-spans in the first view controller trace. This is due to the strange bug in the OS Activity framework used for context propagation.
> Updated view controller instrumentation

- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/Instrumentation/ViewController/TraceLogger.swift
ensure viewcontroller spans use noParent()
removed associated object (no longer necessary)
ensure all contexts associated with viewcontrollers are set with the root viewController instrumentation span
cleans up unnecessary configuration options in agent config.
> shored up viewcontroller instrumentation

- README.md
- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/AgentConfiguration.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
- docs/configuration.asciidoc
changed the way authorization headers are generated, and left backwards compatibility for the existing (deprecated) Agent Configuration.
> Add api key

- Package.swift
- Sources/Instrumentation/CPUSampler/CPUSampler.swift
- Sources/Instrumentation/MemorySampler/MemorySampler.swift
- Sources/apm-agent-ios/Agent.swift
- Sources/apm-agent-ios/Instrumentation/AppMetrics/AppMetrics.swift
- Sources/apm-agent-ios/Instrumentation/ViewController/ViewControllerInstrumentation.swift
OpenTelemetry-swift removed `OpenTelemetrySDK` object, which caused initialization problems, in favor of `OpenTelemetry` object.
> updated otel and removed references to OpenTelemetrySDK

- Sources/apm-agent-ios/Configuration/CentralConfig.swift
- Sources/apm-agent-ios/Configuration/CentralConfigData.swift
this will allow single device configuration of `recording` when the central config values is not set.
> exposes `recording` flag for local use

- Sources/apm-agent-ios/AgentResource.swift
- Sources/apm-agent-ios/ElasticAttributes.swift
instead of combining CFBundleVersion & CFBundleShortVersionString into service.version they will be separated into service.version & service.build.
> added service.build attribute

- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
The `not` operator was incorrectly applied to the signal filters resulting in signals not being sent when they ought to.
> fixed inversion of 'should include' in filter

- CHANGELOG.asciidoc
- docs/release-notes.asciidoc
This change will also need to be cherry-picked to `1.x`.
> remove tech preview from release notes

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
> security: add permissions block to workflows

- Package.swift
- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/Utils/NTPClock.swift
Closes #211 
- replacing TrueTime by Kronos
- sync Kronos Clock and update NTPClock class
- extra log of using Kronos time
> Fix for NTP-related memory leak issues caused by TrueTime library

- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/Instrumentation/CrashReporting/CrashManager.swift
- Sources/apm-agent-ios/Instrumentation/Lifecycle/ApplicationLifecycleInstrumentation.swift
- Sources/apm-agent-ios/InstrumentationWrapper.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticLogRecordProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticSpanProcessor.swift
- Sources/apm-agent-ios/Utils/NetworkStatusManager.swift
I added conditionals for all references to `NetworkStatus` which is only available for iOS based apps, and not available in mac catalyst (iOS apps on mac). This change is inline with the way opentelemetry-swift also includes this component. 
additional issues corrected:
**tvos** : `mach` signal handler is not available on tvos, so `bsd` type is used instead. 
**Lifecycle instrumentation** : only include the lifecycle instrumentation if UIKit is available. This may be extended for AppKit if there is interest. 
Fixes #221
> fixed build issues with tvos and mac

- Sources/apm-agent-ios/Resources/PrivacyInfo.xcprivacy
Added updated purposes, and removed tracking domains field. The domains field is not required because we are not 'tracking' per the definitions provided by Apple: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> updated purpuse of collected data from Analytics to App Functionality

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
Use https://github.com/tibdex/github-app-token to generate ephemeral tokens with the required
permissions only
This is the alternative to moving away from finer-grained GitHub tokens and reducing the
cumbersome of rotating them as we do nowadays.
We have used the same GitHub action in other places.
> github-actions: use GH app to manage the projects

- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
- Sources/apm-agent-ios/Utils/OpenTelemetryHelper.swift
Super seeding @kylemay-gridstone PR
- Support for HTTP connection type was added in #228 but the AgentConfigBuilder doesn't set the connection type from useConnectionType(_:) in the build() method.
- Fixes issue with OpenTelemetryHelper getURL method by removing extraneous "("
- Fixes issue in OpenTelemetryInitializer initializeWithHttp method which does not configure the correct endpoints using "/v1/" for grpc compatibility
> fix: http connection type

- .github/workflows/macos.yml
> the macOS 12 runner image will be removed by December 3rd, 2024
I guess we can use `latest` as we normally are using the latest OS version
Version `14.0` is not available anymore.
> Switching Xcode to version '14.0'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬───────────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │ path                                  │
├─────────┼──────────┼─────────────┼─────────────┼────────┼───────────────────────────────────────┤
│ 0       │ '16.1.0' │ '16B[5](https://github.com/elastic/apm-agent-ios/actions/runs/11381626412/job/31663431612?pr=238#step:2:6)014f'  │ 'Beta'      │ false  │ '/Applications/Xcode_1[6](https://github.com/elastic/apm-agent-ios/actions/runs/11381626412/job/31 …
> ci: use macos-13

- Package.swift
- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/Instrumentation/CrashReporting/CrashManager.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
This PR refactors the CrashManager to use the exporter that is initialized during the OpenTelemetry initialization phase, whether it is GRPC or HTTP.
> CrashExporter doesn't respect connection type setting

- docs/release-notes/index.md
Change `1.0.0` heading to `h2` as the current rendered html looks malformed.
Also, because the "On this page" toc only shows level 2 and 3 headers, it's missing.
> Release notes: Change Heading to H2

- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticLogRecordProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticMetricProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/ElasticSpanProcessor.swift
- Sources/apm-agent-ios/OpenTelementry Extensions/SignalFilter.swift
- Sources/apm-agent-ios/OpenTelemetryInitializer.swift
closes https://github.com/elastic/apm-agent-ios/issues/265
This will facility a way to add attributes global with existing interfaces.
> Allow signal filters to be mutable

- Package.swift
- Sources/apm-agent-ios/ElasticApmAgent.swift
- Sources/apm-agent-ios/Instrumentation/AppMetrics/AppMetrics.swift
- Sources/apm-agent-ios/Instrumentation/CrashReporting/CrashManager.swift
- Sources/apm-agent-ios/Instrumentation/Lifecycle/ApplicationLifecycleInstrumentation.swift
- Sources/apm-agent-ios/Utils/NTPClock.swift
There are several dependencies in the agent that are not supported by watchOS which this agent claims to support. This PR fixes that, as well as updates the supported versions to match more modern usage.
> clean up dependencies and supported platform version

- Sources/Tests/apm-agent-iosTests/utils/OpenTelemetryHelperTests.swift
- Sources/apm-agent-ios/AgentConfigBuilder.swift
- Sources/apm-agent-ios/Utils/OpenTelemetryHelper.swift
fixes #307 
This also fixes a bug where the config overrides the port with `8200` if the exportUrl doesn't specify port, where the expectation should be to fall back on the default ports (`80` or `443`). If a exportUrl/serverUrl isn't provided, it will default to `8200`.
> Respect custom exportUrl path
